/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package progettothreadsgara;

import javax.swing.*;
import java.awt.event.ActionEvent;

/**
 *
 * @author casolaro.diego
 */
public class FRM_Gara extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FRM_Gara.class.getName());

    // Componenti per le macchine
    private JComboBox<String>[] comboTipi;
    private JRadioButton[][] radioTuned; // [macchina][0=normal, 1=tuned]
    private ButtonGroup[] buttonGroups;
    private JProgressBar[] progressBars;
    private JLabel[] labels;
    private JButton btnStart;
    private GuiBarra[] barre;
    private Thread[] threads;
    private Macchine[] macchine;

    /**
     * Creates new form FRM_Gara
     */
    public FRM_Gara() {
        initComponents();
        setupGUI();
    }

    private void setupGUI() {
        int numMacchine = 3;
        comboTipi = new JComboBox[numMacchine];
        radioTuned = new JRadioButton[numMacchine][2];
        buttonGroups = new ButtonGroup[numMacchine];
        progressBars = new JProgressBar[numMacchine];
        labels = new JLabel[numMacchine];
        barre = new GuiBarra[numMacchine];
        threads = new Thread[numMacchine];
        macchine = new Macchine[numMacchine];

        setLayout(null); // Per posizionamento manuale
        setSize(600, 400);

        for (int i = 0; i < numMacchine; i++) {
            // Combo box per tipo
            comboTipi[i] = new JComboBox<>(new String[]{"Da Corsa", "Sleeper", "SUV"});
            comboTipi[i].setBounds(50, 50 + i * 80, 100, 25);
            add(comboTipi[i]);

            // Radio buttons per tuned
            buttonGroups[i] = new ButtonGroup();
            radioTuned[i][0] = new JRadioButton("Normale");
            radioTuned[i][1] = new JRadioButton("Tuned");
            radioTuned[i][0].setSelected(true); // Default normale
            buttonGroups[i].add(radioTuned[i][0]);
            buttonGroups[i].add(radioTuned[i][1]);
            radioTuned[i][0].setBounds(160, 50 + i * 80, 80, 25);
            radioTuned[i][1].setBounds(240, 50 + i * 80, 80, 25);
            add(radioTuned[i][0]);
            add(radioTuned[i][1]);

            // Progress bar
            progressBars[i] = new JProgressBar(0, 100);
            progressBars[i].setBounds(50, 80 + i * 80, 300, 20);
            add(progressBars[i]);

            // Label
            labels[i] = new JLabel("Macchina " + (i+1) + ": 0%");
            labels[i].setBounds(360, 80 + i * 80, 150, 20);
            add(labels[i]);

            barre[i] = new GuiBarra(progressBars[i], labels[i]);
        }

        // Bottone start
        btnStart = new JButton("Inizia Gara");
        btnStart.setBounds(200, 320, 100, 30);
        btnStart.addActionListener(this::btnStartActionPerformed);
        add(btnStart);
    }

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {
        // Crea le macchine
        for (int i = 0; i < 3; i++) {
            String tipoStr = (String) comboTipi[i].getSelectedItem();
            Macchine.TipoMacchina tipo;
            switch (tipoStr) {
                case "Da Corsa":
                    tipo = Macchine.TipoMacchina.DA_CORSA;
                    break;
                case "Sleeper":
                    tipo = Macchine.TipoMacchina.SLEEPER;
                    break;
                default:
                    tipo = Macchine.TipoMacchina.SUV;
                    break;
            }
            boolean tuned = radioTuned[i][1].isSelected();
            macchine[i] = new Macchine(tipo, tuned, "Macchina " + (i+1), barre[i]);
            threads[i] = new Thread((java.lang.Runnable) (Runnable) macchine[i]);
        }

        // Avvia i thread
        for (Thread t : threads) {
            t.start();
        }

        btnStart.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FRM_Gara().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
